const dayFormatter = new Intl.DateTimeFormat('ru-RU', {
  day: 'numeric',
  month: 'short',
  timeZone: 'UTC',
})

const timeFormatter = new Intl.DateTimeFormat('ru-RU', {
  hour: '2-digit',
  minute: '2-digit',
  hour12: false,
  timeZone: 'UTC',
})

const dayKeyFormatter = new Intl.DateTimeFormat('en-CA', {
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
  timeZone: 'UTC',
})

export function formatDay(iso: string): string {
  return dayFormatter.format(new Date(iso))
}

export function formatTime(iso: string): string {
  return timeFormatter.format(new Date(iso))
}

export function dayKey(iso: string): string {
  return dayKeyFormatter.format(new Date(iso))
}

export function feedDayHeading(iso: string, now = new Date()): string {
  const eventDay = dayKey(iso)
  const today = dayKeyFormatter.format(now)
  const yesterdayDate = new Date(now)
  yesterdayDate.setUTCDate(yesterdayDate.getUTCDate() - 1)
  const yesterday = dayKeyFormatter.format(yesterdayDate)

  if (eventDay === today) return 'Сегодня'
  if (eventDay === yesterday) return 'Вчера'
  return formatDay(iso)
}

export function branchFromPayload(payload: Record<string, unknown> | null): string | null {
  if (!payload) return null
  const name = payload.branchName ?? payload.name ?? payload.branch
  return typeof name === 'string' ? name : null
}

export function commitTitleFromPayload(payload: Record<string, unknown> | null): string | null {
  if (!payload) return null
  const title = payload.title ?? payload.message ?? payload.commitMessage
  if (typeof title !== 'string') return null
  const firstLine = title.split('\n')[0]?.trim()
  return firstLine || null
}

function payloadText(
  payload: Record<string, unknown> | null,
  field: string,
): string | null {
  if (!payload) return null
  const value = payload[field]
  if (typeof value === 'string' && value.trim()) return value.trim()
  if (typeof value === 'number') return String(value)
  return null
}

/**
 * Russian detail line for timeline/feed from type + payload.
 * Avoids showing English summaries generated by the backend mapper.
 */
export function eventDetail(
  type: string,
  payload: Record<string, unknown> | null,
): string | null {
  switch (type) {
    case 'BRANCH_CREATED':
      return branchFromPayload(payload)
    case 'COMMIT': {
      const title = commitTitleFromPayload(payload)
      if (title) return title
      const shortId = payloadText(payload, 'shortId')
      return shortId ? `коммит ${shortId}` : null
    }
    case 'MR_OPENED': {
      const iid = payloadText(payload, 'iid')
      return iid ? `открыт MR !${iid}` : null
    }
    case 'MR_APPROVED': {
      const iid = payloadText(payload, 'iid')
      return iid ? `одобрен MR !${iid}` : null
    }
    case 'MR_MERGED': {
      const iid = payloadText(payload, 'iid')
      return iid ? `смержен MR !${iid}` : null
    }
    default:
      return null
  }
}
